### PR TITLE
Notification Model

### LINKED ISSUE #55: Notification Model
### Issuer:
Hung Ngoos
### Assignee(s):
Ngoc Anh

### Requirements:
- [ ] Please list what tasks need to be done (be specific here)
- [ ] Create a Notification Model expressing one-to-one relationship with the User but the User will have one-to-many Notifications. 
- [ ] Create a Notification provider on frontend to check if user has any notifications pending
- [ ] Delete any resolved notifications
- [ ] Create new notifications for each requests that is considered as time consuming

### Dependencies:
- Please list the files that might be involved in this issue
- Mongoose
- Express

### Done requirements:
- When will this issue count as done?
-When the flow is complete between frontend and backend.

### PR DESCRIPTION
**Pull request by Anhtran0208**
1. Features: 
- Users upload the receipt and receive real-time notification when the receipt is done without waiting or staying on that page. 
- Users can view the number of unread notification and a list of them. For each notification, if they click to it, it will mark it as read. They can also delete it. The number of notifications in header is also updated.
2. Demo: 
https://www.loom.com/share/1cc175ed48c949aeaabe2de23c32287e
3. Files I changed: 
- Refactor scan-receipts folder to make it shorter and clearer
- Backend:
  + model => NotificationModel: create a notification model in database with status read or unread and store result of each notification when the receipt is done 
  + notificationController: to get the current unread notification and get the detail of each of them
  + socketio.ts: get real time notification when the receipt is done, update the number of notification when user mark is as read or delete it
- Frontend: 
  + components => NotificationDetail/NotificationList: display detail of notification (right now, it just displayed the raw data but after that, we will connect with form Vien did) and list of unread notifications respectively
  + components => UploadReceiptForm: just create it for testing, will connect with image scan feature of chi Vy 
  + context => NotificationContext: create to pass data related to notification as props 
  + context => ToastContext: create to display toastify globally (users can see the toast no matter what page they are on)
  + page: NotificationDetail, NotificationPage, ReceiptScan
  + providers: NotificationProvider, ToastProvider, SocketProvider
  + socketio.tsx: set up socket

### CODE REVIEW

**Comment by Anhtran0208** [comment]
update: connected with Image Scan of chi Vy

**Comment by Anhtran0208** [comment]
Please ignore pyc files because it was just what is generated when running python

**Review by hungngodev — APPROVED** [review]
Everything is good, now just connect with Vien receipt form and it will be done.

**Comment by Anhtran0208** [comment]
update: connected to Vien's form, but there are some issues: 
1. When users reload the page, the data is lost and it got the error that "img" field is undefined. If users want to continue editing again, they need to click the notification in the list. I tried to use "reset" in react-hook-form" to keep the data, but when doing that, the field is not editable. Will try to look into more. 
2. When users want to edit ingredients' name extracted from receipts, it is not updated. Same situation when they want to add new items. Asked Vien to take a look. 
3. I also wrote backend functions for searching in MongoDB, tested it with Postman and it worked. But now, since edit ingredients function does not work, it doesn't work on frontend. 
4. When users change suggestions, the image is not updated, but I think Vien set the value as the image of the first suggestion. Asked him to take a look
Example when testing Postman: 
image
Demo to connect the form:
https://www.loom.com/share/c1f418dd286c44489f1c3866a25e39a1

**Pull request merged**
