### PR TITLE
Today specialty task

### LINKED ISSUE #30: Today specialty
### Issuer:
Hung Ngoos
### Requirements:
- [ ] please list what tasks need to be done (be specific here)
- 
image

Create UI of your choice. Mock data of name, description, image with something that you want. 

### Dependencies:
- Please list the files that might be involved in this issue
- Charka UI 

### Done requirements:
- When will this issue count as done?

### PR DESCRIPTION
**Pull request by Anhtran0208**
today-specialty
Current UI

### CODE REVIEW

**Comment by Anhtran0208** [comment]
added link and id to the button

**Comment by thuyvy119** [comment]
I think words inside the tags should be fitted in the frame. Also, it would be better if there is little spacing between today specialty's section and search bar.

**Comment by Anhtran0208** [comment]
> I think words inside the tags should be fitted in the frame. Also, it would be better if there is little spacing between today specialty's section and search bar.

thank you chi for your comment. Updated

**Comment by Anhtran0208** [comment]
today-specialty

**Review by hungngodev — CHANGES_REQUESTED** [review]
Great UI but could you make it pop up gradually with some animation to make it smooth? Hint: you could use some framer motion basic animation or may be just some tailwind CSS like transition-all since I have integrated tailwind.

**Comment by Anhtran0208** [comment]
updated UI with animation 
today-specialty

**Review by hungngodev — APPROVED** [review]
This is a beautiful animation!

**Pull request merged**
