### PR TITLE
User info card

### LINKED ISSUE #28: User Info Card
### Issuer:
Hung Ngoos
### Requirements:
- [ ] please list what tasks need to be done (be specific here)
image

Create UI Like this! create mock data that has name, description, and any information of your choice. But try to generalize it by adding props. 

### Dependencies:
- Please list the files that might be involved in this issue
- Charka UI, and many resources link

### Done requirements:
- When will this issue count as done?

### PR DESCRIPTION
**Pull request by thuyvy119**
Close #28 
- Create user profile card with UserProps storing users' name, avatar, email, mobile phone number, zipcode, and their address (city, state and country).
- The card contains a flex box, a box with divider and card body:
  - Flex box: 
    - A flex box comprising of avatar and a box stacked horizontally (box has users' name as heading and the city, state where they live).
    - A icon button if user want to adjust their info.
  - Card body: 2 boxes stacked horizontally. 1 box display feature's title (e.g: Email, Phone, City, State, etc), another one shows the corresponding user's information.

Userinforcard

### CODE REVIEW

**Review by hungngodev — CHANGES_REQUESTED** [review]
- Great work so far. You can now merge the conflicts and link the pull request with the issue

**Review by hungngodev — CHANGES_REQUESTED** [review]
Please bring the code in App.tsx to the component files of this component! Same thing for card meal.

**Comment by thuyvy119** [comment]
Done.

**Review by hungngodev — APPROVED** [review]
Great work!!!

**Review by hungngodev — CHANGES_REQUESTED** [review]
For some reasons, there is still conflict BUTTT go to sleep please, your health is precious!!!

**Review by hungngodev — APPROVED** [review]
Thank you!! This is beautiful change

**Pull request merged**
