### PR TITLE
finish image-scan backend

### PR DESCRIPTION
**Pull request by Anhtran0208**
An example of response data: 
{
    "message": "Image processed successfully",
    "data": {
        "items": [
            {
                "name": "Lorem ipsum",
                "price": "$9.20",
                "quantity": "1"
            },
            {
                "name": "Lorem ipsum dolor sit",
                "price": "$19.20",
                "quantity": "1"
            },
            {
                "name": "Lorem ipsum dolor sit amet",
                "price": "$15.00",
                "quantity": "1"
            },
            {
                "name": "Lorem ipsum",
                "price": "$15.00",
                "quantity": "1"
            },
            {
                "name": "Lorem ipsum dolor sit",
                "price": "$15.00",
                "quantity": "1"
            },
            {
                "name": "Lorem ipsum",
                "price": "$19.20",
                "quantity": "1"
            }
        ],
        "total": "$107.60"
    }
}

### CODE REVIEW

**Comment by Anhtran0208** [comment]
How to test:
1. Open a terminal: cd scan-receipts => python app.py to run server of Flask. Make sure the server is running without error
2. Open another terminal: cd src => npm run server to run server of Nodejs
3. In Postman, choose method POST, enter URL: http://localhost:5100/api/scan-receipt. In Body tab, choose form-data, enter "receipt" in key and upload an image in value. Click Send

**Review by hungngodev — APPROVED** [review]
Mergingingin

**Review by hungngodev — CHANGES_REQUESTED** [review]
Adding the code for installing package in the "set-up-production-app" and add the code to "dev"

**Review by hungngodev — APPROVED** [review]
DONEEEE!! THANKSSS NGOC ANH

**Pull request merged**
