### PR TITLE
Feature/User page

### PR DESCRIPTION
**Pull request by thuyvy119**
# Description
- Added heading for allergy and diets tags in TagSelect and adjust fontsize in CustomTags.
- Created a list of recent meals.
- Generated a table of daily analysis according to 3 meal types (breakfast, lunch, dinner) and a polar area chart for daily summary of nutrition.
-  Created a weekly summary (3 progress boxes and a bar chart) for some main nutrients: protein, carbs, fat and calories.
- Wrapped user card, allergy and diet tags, daily analysis (table), daily summary (polar area chart) and weekly summary in User function.

## Issues

https://github.com/hungngodev/Flavorie/assets/45311428/d45d56cf-776d-4fd1-944f-64082e411022

## Test

Copy this mock data to App.tsx

```typescript
const PersonalDashboardWrapper = () => {
 const userInfo = {
   avatar: {
     src: "../public/images/1989-Taylors-Version.webp",
     username: "Alex B",
   },
   email: "taylorswift@gmail.com",
   phone: "+1 (202) 444 1989",
   address: {
     city: "Nashville",
     state: "Tennessee",
     country: "USA",
     zipcode: "37208",
   },
 };


 const Dailydata = [
   {
     mealType: 'Breakfast',
     calories: 120.4,
     carbs: 53.7,
     protein: 62.4,
     fat: 14.5,
   },
   {
     mealType: 'Lunch',
     calories: 280.6,
     carbs: 130.7,
     protein: 136.2,
     fat: 18.4,
   },
   {
     mealType: 'Dinner',
     calories: 220.7,
     carbs: 89.4,
     protein: 100.9,
     fat: 19.8,
   }
 ];


 const recentMeals = [
   {
     image: 'https://www.chilipeppermadness.com/wp-content/uploads/2023/12/Bun-Bo-Hue-Recipe1.jpg',
     title: 'Bun bo Hue',
     calories: 550,
     date: '04/28/2024',
     infoLink: 'https://www.chilipeppermadness.com/recipes/bun-bo-hue/',
   },
   {
     image:
       'https://assets.bonappetit.com/photos/6437281f4c497b684ece7ff3/1:1/w_2240,c_limit/Recipe_Beauty_Gingery_Chicken_Ramen_0350.jpg',
     title: 'Ramen',
     calories: 400,
     date: '04/22/2024',
     infoLink: 'https://www.bonappetit.com/recipe/homemade-chicken-ramen-recipe',
   },
   {
     image: 'https://joyfoodsunshine.com/wp-content/uploads/2022/11/BBQ-chicken-pizza-recipe-8.jpg',
     title: 'Pizza',
     calories: 780,
     date: '04/18/2024',
     infoLink: 'https://joyfoodsunshine.com/bbq-chicken-pizza/',
   },
   {
     image: 'https://www.budgetbytes.com/wp-content/uploads/2013/07/Creamy-Tomato-Spinach-Pasta-V2-bowl.jpg',
     title: 'Pasta',
     calories: 600,
     date: '04/15/2024',
     infoLink: 'https://www.budgetbytes.com/wp-content/uploads/2013/07/Creamy-Tomato-Spinach-Pasta-V2-bowl.jpg',
   },
   {
     image: 'https://preppykitchen.com/wp-content/uploads/2022/05/Naked-Cake-Blog2.jpg',
     title: 'Naked Cake',
     calories: 600,
     date: '04/12/2024',
     infoLink: 'https://preppykitchen.com/wp-content/uploads/2022/05/Naked-Cake-Blog2.jpg',
   },
   {
     image:
       'https://img.taste.com.au/4F5Z2H_-/w720-h480-cfill-q80/taste/2016/11/aussie-style-beef-and-salad-tacos-86525-1.jpeg',
     title: 'Tacos',
     calories: 600,
     date: '03/28/2024',
     infoLink:
       'https://img.taste.com.au/4F5Z2H_-/w720-h480-cfill-q80/taste/2016/11/aussie-style-beef-and-salad-tacos-86525-1.jpeg',
   },
   {
     image: 'https://www.chilipeppermadness.com/wp-content/uploads/2023/12/Bun-Bo-Hue-Recipe1.jpg',
     title: 'Bun bo Hue',
     calories: 550,
     date: '04/28/2024',
     infoLink: 'https://www.chilipeppermadness.com/recipes/bun-bo-hue/',
   },
   {
     image:
       'https://assets.bonappetit.com/photos/6437281f4c497b684ece7ff3/1:1/w_2240,c_limit/Recipe_Beauty_Gingery_Chicken_Ramen_0350.jpg',
     title: 'Ramen',
     calories: 400,
     date: '04/22/2024',
     infoLink: 'https://www.bonappetit.com/recipe/homemade-chicken-ramen-recipe',
   },
 ];


 const weeklyData = {
   weeklyProtein: 70,
   weeklyCarb: 50,
   weeklyFat: 30,
 };


 const weeklyCalories = [
   { date: 'Mon', weeklyCalories: '200' },
   { date: 'Tue', weeklyCalories: '250' },
   { date: 'Wed', weeklyCalories: '300' },
   { date: 'Thu', weeklyCalories: '280' },
   { date: 'Fri', weeklyCalories: '350' },
   { date: 'Sat', weeklyCalories: '400' },
   { date: 'Sun', weeklyCalories: '370' },
 ];


 const dashboardProps = {
   mealData: Dailydata,
   info: userInfo,
   totalMeals: '12',
   points: '34',
   tags: 'diet',
   reviewsGiven: '10',
   recipesShared: '8',
   caloriesConsumed: '5420',
   badgesEarned: 'First popular shared',
   recentMeals: recentMeals,
   protein: '210',
   vitamins: '48',
   carb: '190',
   fat: '120',
   minerals: '42',
   weeklySummaryData: weeklyData,
   weeklyCaloriesData: weeklyCalories
 }
 return  <User {...dashboardProps}/>;
};
```

## Possible Downsides

Achievements section will be changed later, also the tags might be adjusted (reduce size). Background and charts' colors will be changed after selecting color palette. 

## Additional Documentations
https://www.chartjs.org/docs/latest/samples/other-charts/polar-area.html
https://www.chartjs.org/docs/latest/charts/bar.html

### CODE REVIEW

**Comment by viennguyen24** [comment]
Hi Vy, great work on the user page! I just have some quick notice about the UI

- I think it would look more consistent if each grid element is wrapped in a container card like the User Info card (with a light border and box shadow) to separate each item, and more gap between each grid can be added to let the elements breathe a bit more. 
- On the second column, I personally think it would be better if the order of the cards was (top to bottom): achievements, meal nutrition, recent meals. Your achievements should be the first thing you see, and then the two tables can be placed near each other because they are relatively similar. Also, you can try to highlight the achievements a bit more [here's duolingo's achievement page as my suggestion (notice the small Statistics card)](https://i.pinimg.com/736x/49/6b/7f/496b7fd6dfaa019d88caaf9b5abcf534.jpg)
- Remember to link the PR

Great use of chart.js !

**Comment by thuyvy119** [comment]
Hi Vien, thank you so much for your comment. 
I think we need to discuss more about which features should be displayed in achievements section in the meeting tonight.

**Review by hungngodev — CHANGES_REQUESTED** [review]
This is a really fantastic work considering you have to create a whole new page. 
However, you need to cover some cases: what if the user is new, that user have not cooked any meals so how would you display it in the recent meals let aside other components.  You could leave some notes as: Lets cooking some meal, in the chart, you may replace with lets cook then we will analyze your nutrition, etc.

**Comment by thuyvy119** [comment]
Updated user dashboard will look like this
Screenshot 2024-06-15 at 01 01 20

Already added text for new user in recent meal, daily summary or weekly summary.

**Pull request closed without merging**
